fix image build in CDK (#146)
*Issue #, if available:*

*Description of changes:*

Fix the image build issue due to permissions: 

```
ValidationError: Failed to bundle asset LambdaPetClinicStack/GetAppointmentVersioning/VersionHandler/Code/Stage, bundle output is located at
  /local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/cdk.out/asset.64f06d48a4bd71ee4b9d3d88aa28f6289151032ee882cb15165894818dec02be-building: ExecutionError: docker exited with
  status 243
  --> Command: docker run --rm -u "11896572:100" -v "/local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/src/lambda-version-handler:/asset-input:delegated" -v
  "/local/home/pinxiang/test-slo/application-signals-demo/lambda-petclinic/cdk/cdk.out/asset.64f06d48a4bd71ee4b9d3d88aa28f6289151032ee882cb15165894818dec02be-building:/asset-output:delegated" -w
  "/asset-input" "public.ecr.aws/sam/build-nodejs20.x" bash -c "npm install && cp -r . /asset-output/"
      at path [LambdaPetClinicStack/GetAppointmentVersioning/VersionHandler/Code/Stage] in aws-cdk-lib.AssetStaging
```


By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.